import { RoleCode } from '../../../types/enums'
import { NotificationItem } from './types'

export const initialNotifications: NotificationItem[] = [
  // === DÀNH RIÊNG CHO SUPERVISOR (GIÁM SÁT / CĐT) ===
  {
    id: 'notif-sup-01',
    category: 'ACTION_REQUIRED',
    categoryLabel: 'Yêu cầu thẩm duyệt',
    title: 'Bàn giao thẩm duyệt Gói đề xuất sửa chữa đợt 3 (PKG-2026-08)',
    message: 'PM Đỗ Quốc Hoàng đã hoàn tất lập hồ sơ thiết kế BOQ 4 hạng mục trên QL1A Km 1032. Hồ sơ đang chờ Supervisor thẩm định và phê duyệt theo FR-19.',
    resourceType: 'REPAIR_PROPOSAL',
    resourceId: 'PKG-2026-08',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1032+450',
    sender: 'Kỹ sư Đỗ Quốc Hoàng (PM)',
    senderRole: 'Project Manager',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'HIGH',
    slaHoursRemaining: 3.5,
    slaType: 'SLA-APPR-48h',
    read: false,
    occurredAt: '15 phút trước',
    timeAgo: '15 phút trước',
    actionUrl: '/sup/proposals/PKG-2026-08',
    actionLabel: 'Thẩm duyệt hồ sơ ngay'
  },
  {
    id: 'notif-sup-02',
    category: 'HANDOVER',
    categoryLabel: 'Bàn giao nghiệm thu',
    title: 'Bàn giao Biên bản nghiệm thu thi công hiện trường (ACC-2026-04)',
    message: 'Đội thi công sửa chữa Hoàng Hải 01 đã nộp đủ bộ ảnh Trước/Sau kèm mã hash SHA-256 đối chiếu 3 hạng mục thảm bê tông nhựa. Chờ Supervisor nghiệm thu hiện trường.',
    resourceType: 'ACCEPTANCE_DOSSIER',
    resourceId: 'ACC-2026-04',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1025+000 - Km 1026+500',
    sender: 'Kỹ sư Kiên (Chỉ huy đội 01)',
    senderRole: 'Đội thi công Hoàng Hải',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'HIGH',
    slaHoursRemaining: 18.0,
    slaType: 'SLA-ACCEPT-72h',
    read: false,
    occurredAt: '1 giờ trước',
    timeAgo: '1 giờ trước',
    actionUrl: '/sup/acceptance',
    actionLabel: 'Kiểm tra biên bản nghiệm thu'
  },
  {
    id: 'notif-sup-03',
    category: 'ACTION_REQUIRED',
    categoryLabel: 'Xác nhận tuyến',
    title: 'Yêu cầu thẩm định & Khóa phiên bản tim tuyến (RoadSectionVersion v2.1)',
    message: 'PM Đỗ Quốc Hoàng đã hoàn tất cập nhật tim đường GPX và chia phân đoạn Km 1020 - Km 1045. Đang chờ Supervisor thẩm tra và bấm Khóa xác nhận (LOCK) theo FR-07.',
    resourceType: 'FIELD_TASK',
    resourceId: 'ALIGN-2026-02',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1020+000 - Km 1045+000',
    sender: 'PM Đỗ Quốc Hoàng',
    senderRole: 'Project Manager',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'HIGH',
    slaHoursRemaining: 6.0,
    slaType: 'SLA-APPR-48h',
    read: false,
    occurredAt: '45 phút trước',
    timeAgo: '45 phút trước',
    actionUrl: '/sup/alignment',
    actionLabel: 'Thẩm tra & Khóa tuyến'
  },
  {
    id: 'notif-sup-04',
    category: 'HANDOVER',
    categoryLabel: 'Ký số đóng đợt',
    title: 'Hồ sơ đủ điều kiện Ký số đóng đợt sửa chữa (Sign-off Ready)',
    message: 'Đợt sửa chữa PKG-2026-05 đã hoàn thành 100% hạng mục đạt tiêu chuẩn nghiệm thu hiện trường (PASSED). Hồ sơ pháp lý đã sẵn sàng để Supervisor cắm chữ ký số đóng đợt theo FR-23.',
    resourceType: 'ACCEPTANCE_DOSSIER',
    resourceId: 'SIGNOFF-PKG-05',
    routeCode: 'QL1A • PK-04',
    stationing: 'Toàn tuyến PK-04',
    sender: 'Ban Quản Lý Chất Lượng Hoàng Hải',
    senderRole: 'Hệ thống kiểm soát nghiệm thu',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'HIGH',
    slaHoursRemaining: 12.0,
    slaType: 'SLA-ACCEPT-72h',
    read: false,
    occurredAt: '2 giờ trước',
    timeAgo: '2 giờ trước',
    actionUrl: '/sup/signoff',
    actionLabel: 'Mở màn hình Ký số đóng đợt'
  },
  {
    id: 'notif-sup-05',
    category: 'ACTION_REQUIRED',
    categoryLabel: 'Cảnh báo rủi ro',
    title: 'CẢNH BÁO RỦI RO: Đoạn Km 1028 - Km 1030 suy thoái chỉ số PCI vượt ngưỡng',
    message: 'Hệ thống phân tích rủi ro phát hiện chỉ số rủi ro bảo hành tăng 24% sau đợt mưa lũ. Đề nghị Supervisor kích hoạt chế độ giám sát trọng điểm và yêu cầu PM lập kế hoạch dự phòng.',
    resourceType: 'DEFECT',
    resourceId: 'RISK-ALERT-09',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1028+000 - Km 1030+000',
    sender: 'Hệ thống Phân tích Rủi ro & Suy thoái',
    senderRole: 'AI Risk Engine',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'EMERGENCY',
    slaHoursRemaining: 2.0,
    slaType: 'SLA-EMERG-2h',
    read: false,
    occurredAt: '1 giờ trước',
    timeAgo: '1 giờ trước',
    actionUrl: '/sup/risk-analytics',
    actionLabel: 'Xem bản đồ phân tích rủi ro'
  },
  {
    id: 'notif-sup-06',
    category: 'AI_SYSTEM',
    categoryLabel: 'Chất lượng bay Drone',
    title: 'Báo cáo tổng hợp chất lượng ảnh bay Drone chuyến QL1A-MS-04B',
    message: 'Chuyến bay đã nộp dữ liệu video 4K kèm file phụ đề SRT telemetry đầy đủ. Tỷ lệ phủ ảnh đạt 98.2%, độ cao bay trung bình 25m, sai số vị trí < 1.2m.',
    resourceType: 'SURVEY_MISSION',
    resourceId: 'QL1A-MS-04B',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1024 - Km 1030',
    sender: 'Tổ bay Drone Hoàng Hải',
    senderRole: 'Drone Flight Operator',
    recipientRole: RoleCode.SUPERVISOR,
    priority: 'NORMAL',
    read: true,
    occurredAt: '4 giờ trước',
    timeAgo: '4 giờ trước',
    actionUrl: '/sup/surveys',
    actionLabel: 'Xem chi tiết chuyến bay'
  },

  // === DÀNH RIÊNG CHO PROJECT MANAGER (PM CHỈ HUY TRƯỞNG) ===
  {
    id: 'notif-pm-01',
    category: 'ACTION_REQUIRED',
    categoryLabel: 'Cảnh báo khẩn cấp',
    title: 'LỆNH ỨNG CỨU KHẨN CẤP: Ổ gà sụt sâu nguy cơ nổ lốp xe tải',
    message: 'Phát hiện ổ gà sâu 8.5cm tại Km 1033+110 làn xe tải nặng. Yêu cầu Đội cơ động số 03 lập tức xuất quân rào chắn, đổ đá dăm thông xe tạm thời trong 2 giờ.',
    resourceType: 'DEFECT',
    resourceId: 'DEF-2026-0105',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1033+110 (Làn phải R1)',
    sender: 'Tuần tra viên Lê Tuấn',
    senderRole: 'Đội tuần đường QL1A',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'EMERGENCY',
    slaHoursRemaining: 1.2,
    slaType: 'SLA-EMERG-2h',
    read: false,
    occurredAt: '35 phút trước',
    timeAgo: '35 phút trước',
    actionUrl: '/pm/fast-track',
    actionLabel: 'Điều phối xuất quân khẩn cấp'
  },
  {
    id: 'notif-pm-02',
    category: 'AI_SYSTEM',
    categoryLabel: 'Xử lý dữ liệu AI',
    title: 'Hoàn tất phân tích Video AI chuyến bay quét QL1A-MS-04B',
    message: 'Mô hình Road-YOLOv9 đã phát hiện 8 khiếm khuyết sơ bộ (2 ổ gà, 3 nứt dọc, 1 hằn lún). Tuyến đạt tỷ lệ phủ ảnh 98% (Không còn điểm mù).',
    resourceType: 'SURVEY_MISSION',
    resourceId: 'QL1A-MS-04B',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1024+000 - Km 1030+000',
    sender: 'Hệ thống Drone AI Road-YOLOv9',
    senderRole: 'AI Analytics Server',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'NORMAL',
    read: false,
    occurredAt: '2 giờ trước',
    timeAgo: '2 giờ trước',
    actionUrl: '/pm/drone-mission',
    actionLabel: 'Mở giao diện thẩm định AI'
  },
  {
    id: 'notif-pm-03',
    category: 'HANDOVER',
    categoryLabel: 'Phản hồi phê duyệt',
    title: 'Supervisor đã chấp thuận Phương án kỹ thuật Gói PKG-2026-07',
    message: 'Tư vấn giám sát đã duyệt 3/3 hạng mục dự toán BOQ và mở khóa trạng thái APPROVED. PM có thể tiến hành phân công Đội thi công ra hiện trường.',
    resourceType: 'REPAIR_PROPOSAL',
    resourceId: 'PKG-2026-07',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1028+900',
    sender: 'Supervisor GS-2041 (Ban QLDA)',
    senderRole: 'Giám sát trưởng',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'NORMAL',
    read: true,
    occurredAt: '3 giờ trước',
    timeAgo: '3 giờ trước',
    actionUrl: '/pm/proposals',
    actionLabel: 'Xem chi tiết gói đã duyệt'
  },
  {
    id: 'notif-pm-04',
    category: 'FIELD_CREW',
    categoryLabel: 'Báo cáo hiện trường',
    title: 'Hoàn tất nhiệm vụ đo đạc trắc địa bổ sung (TSK-2026-018)',
    message: 'Tổ đo đạc 02 đã hoàn thành đo kích thước cơ khí 4 vị trí nứt rạn lưới mai tại Km 1029+400. Đã cập nhật số đo chiều dài 7.0m, khe nứt 2.8mm vào hồ sơ.',
    resourceType: 'FIELD_TASK',
    resourceId: 'TSK-2026-018',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1029+400',
    sender: 'Kỹ sư Minh (Tổ đo đạc 02)',
    senderRole: 'Đội đo đạc chuyên dụng',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'NORMAL',
    read: true,
    occurredAt: '5 giờ trước',
    timeAgo: '5 giờ trước',
    actionUrl: '/pm/field-tasks',
    actionLabel: 'Xem dữ liệu đo đạc'
  },
  {
    id: 'notif-pm-05',
    category: 'ACTION_REQUIRED',
    categoryLabel: 'Nhắc việc SLA Fast Track',
    title: 'Cảnh báo sắp hết hạn SLA 24h: Vá dặm nguội ổ gà Km 1024+350',
    message: 'Lệnh Fast Track mã #DEF-2026-0101 giao cho Tổ 01 còn lại 4.5 giờ để hoàn tất và tải ảnh nghiệm thu Sau (AFTER). Yêu cầu kỹ sư đôn đốc tiến độ.',
    resourceType: 'DEFECT',
    resourceId: 'DEF-2026-0101',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1024+350',
    sender: 'Hệ thống kiểm soát SLA',
    senderRole: 'Quy tắc BR-08',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'HIGH',
    slaHoursRemaining: 4.5,
    slaType: 'SLA-FT-24h',
    read: false,
    occurredAt: '6 giờ trước',
    timeAgo: '6 giờ trước',
    actionUrl: '/pm/fast-track',
    actionLabel: 'Đôn đốc tổ hiện trường'
  },
  {
    id: 'notif-pm-06',
    category: 'HANDOVER',
    categoryLabel: 'Yêu cầu sửa đổi hồ sơ',
    title: 'Yêu cầu điều chỉnh hồ sơ gói PKG-2026-06 (REVISION_REQUIRED)',
    message: 'Supervisor từ chối hạng mục bù bê tông nhựa do đơn giá nhân công lu lèn chưa đúng định mức Bộ GTVT. PM vui lòng điều chỉnh lại dự toán chi tiết.',
    resourceType: 'REPAIR_PROPOSAL',
    resourceId: 'PKG-2026-06',
    routeCode: 'QL1A • PK-04',
    stationing: 'Km 1030+200',
    sender: 'Supervisor GS-2041',
    senderRole: 'Giám sát trưởng',
    recipientRole: RoleCode.PROJECT_MANAGER,
    priority: 'HIGH',
    read: true,
    occurredAt: 'Hôm qua',
    timeAgo: 'Hôm qua',
    actionUrl: '/pm/proposals',
    actionLabel: 'Chỉnh sửa hồ sơ dự toán'
  }
]
