// GENERATED by build_contracts.py from openapi.baseline.yaml. Do not edit.
// Source SHA256: dd991f20c9a27a564bf37c06bba63776424b770f3abfa54ec2bef9d1a1e678bd
// Structural TS only: use JSON Schema for formats/ranges/oneOf and runtime validation.

export type ErrorDetail = { "field"?: string; "code": string; "message": string; };

/** Không chứa stacktrace, PII, secrets hoặc giá trị password/token. */
export type Error = { "code": string; "message": string; "details": Array<ErrorDetail>; "traceId": string; "retryable": boolean; };

export type Ack = { "id": string; "status": "ACCEPTED"; "version": string; };

/** WGS84; tên thuộc tính tránh đảo lat/lon; GeoJSON position array bên dưới là lon,lat. */
export type Point = { "longitude": number; "latitude": number; };

export type Position = { "point": Point; "source": "EXIF" | "MANUAL" | "SURVEY" | "DERIVED"; "accuracyMeters"?: (number | null); "capturedAt"?: (string | null); };

export type Actor = { "id": string; "displayName": string; "role": "SUPERVISOR" | "PM" | "OPERATOR" | "CREW" | "REPORTER"; "version": string; };

export type LoginRequest = { "email": string; "password": string; };

export type TokenPair = { "accessToken": string; "refreshToken": string; "tokenType": "Bearer"; "expiresIn": number; "mustChangePassword": boolean; "user": Actor; };

export type RefreshRequest = { "refreshToken": string; };

/** reporterType phải thuộc danh mục ReporterType đã đối chiếu DD; không mở role input. */
export type RegisterReporter = { "email": string; "password": string; "displayName": string; "reporterType": string; };

/** Cùng shape cho địa chỉ tồn tại, không lộ account; intent opaque không cấp business access. */
export type RegistrationIntent = { "intentId": string; "status": "PENDING_VERIFICATION"; "resendAfterSeconds": number; };

export type VerifyOtp = { "intentId": string; "otp": string; };

export type ResendOtp = { "intentId": string; };

export type ChangePassword = { "currentPassword": string; "newPassword": string; };

/** Supervisor thực hiện; truyền TLS, không echo/log password. Buộc đổi ở lần login tiếp theo. */
export type ResetPassword = { "temporaryPassword": string; "reason": string; };

/** Tạo yêu cầu khôi phục, không tự reset; luôn trả 202 trung tính. */
export type ForgotPassword = { "email": string; };

export type InvitationRequest = { "email": string; "role": "PM" | "OPERATOR" | "CREW" | "SUPERVISOR"; "projectIds": Array<string>; };

export type Invitation = { "id": string; "status": "PENDING" | "ACCEPTED" | "EXPIRED" | "REVOKED"; "expiresAt": string; "version": string; };

export type AcceptInvitation = { "invitationToken": string; "displayName": string; "password": string; };

export type ProfileUpdate = { "displayName": string; };

export type AccountUpdate = { "status": "ACTIVE" | "SUSPENDED"; "role": "SUPERVISOR" | "PM" | "OPERATOR" | "CREW" | "REPORTER"; "reason": string; };

export type MembershipRequest = { "userId": string; "role": "PM" | "OPERATOR" | "CREW"; "active": boolean; "validFrom": string; "validTo"?: (string | null); "reason": string; };

export type Membership = { "id": string; "projectId": string; "userId": string; "role": string; "active": boolean; "version": string; };

/** Supervisor tạo; warrantyEndDate>=handoverDate; chỉ định đúng một PM chính. */
export type ProjectCreate = { "code": string; "name": string; "primaryPmId": string; "handoverDate": string; "warrantyEndDate": string; "handoverFileIds": Array<string>; };

export type Project = { "id": string; "code": string; "name": string; "primaryPmId": string; "handoverDate": string; "warrantyEndDate": string; "status": "ACTIVE" | "CLOSED"; "version": string; };

export type ProjectUpdate = { "name": string; "primaryPmId": string; "warrantyEndDate": string; "reason": string; };

export type Reason = { "reason": string; };

export type WidthInterval = { "startMeters": number; "endMeters": number; "roadWidthMeters": number; };

export type GeoJsonLine = { "type": "LineString"; "coordinates": Array<[number, number]>; };

/** Cần sourceFileId hoặc centerline; sourceFileId GPX nhiều track cần trackId; centerline luôn WGS84, sourceCrs mô tả bản gốc. Backend chuyển metricCrs đã kiểm chứng. Không lấy tổng corridor làm road width. */
export type RouteDraftRequest = { "sourceFileId"?: string; "trackId"?: string; "sourceCrs": string; "metricCrs": string; "centerline"?: GeoJsonLine; "stationOriginMeters": number; "widthIntervals": Array<WidthInterval>; "surveyTotalWidthMeters": number; };

export type RouteVersion = { "id": string; "projectId": string; "status": "DRAFT" | "CONFIRMED"; "centerline": GeoJsonLine; "metricCrs": string; "widthIntervals": Array<WidthInterval>; "surveyTotalWidthMeters": number; "sourceFileId": (string | null); "version": string; };

/** Đúng một trong targetLengthMeters hoặc boundariesMeters; boundary tăng, phủ tuyến không hở/chồng. */
export type SegmentRequest = ({ "routeVersionId": string; "targetLengthMeters": number; "boundariesMeters"?: never; } | { "routeVersionId": string; "targetLengthMeters"?: never; "boundariesMeters": Array<number>; });

export type Segment = { "id": string; "startMeters": number; "endMeters": number; };

export type SegmentSet = { "id": string; "routeVersionId": string; "status": "DRAFT" | "PUBLISHED"; "segments": Array<Segment>; "version": string; };

export type BranchRequest = { "code": string; "routeVersionId": string; "startNodeId"?: (string | null); "endNodeId"?: (string | null); "connectionReason": string; };

export type Branch = { "id": string; "projectId": string; "code": string; "routeVersionId": string; "version": string; };

/** Không hard-code 4m; xác nhận cần dữ liệu khe/hoàn công theo Q10. */
export type SlabRequest = { "routeVersionId": string; "laneCode": string; "startMeters": number; "endMeters": number; "status": "PROVISIONAL" | "CONFIRMED"; "sourceFileIds": Array<string>; };

export type Slab = { "id": string; "projectId": string; "routeVersionId": string; "laneCode": string; "startMeters": number; "endMeters": number; "status": "PROVISIONAL" | "CONFIRMED"; "version": string; };

/** Thiếu EXIF không dùng GPS upload; có thể lưu thiếu vị trí chờ điều phối với nhãn thiếu. */
export type ReportPhoto = { "fileId": string; "position"?: Position; };

export type ReportCreate = { "description": string; "photos": Array<ReportPhoto>; "suggestedProjectId"?: string; };

/** Projection của Reporter không trả owner người khác hoặc internal case. */
export type IncidentReport = { "id": string; "ownerId": string; "caseId": string; "receivedAt": string; "status": "RECEIVED" | "IN_REVIEW" | "PUBLISHED"; "version": string; };

export type PublicEvent = { "id": string; "occurredAt": string; "message": string; "publishedFileIds": Array<string>; };

export type PublicReport = { "id": string; "description": string; "status": string; "events": Array<PublicEvent>; "version": string; };

/** Nội bộ; enum vòng đời cần khóa với DD. Không trả object này cho Reporter. */
export type Case = { "id": string; "projectId": (string | null); "reportIds": Array<string>; "defectIds": Array<string>; "status": string; "version": string; };

/** PM xác nhận, cùng scope; giữ ownership/source. Không merge tự động. */
export type LinkReports = { "reportIds": Array<string>; "primaryCaseId": string; "reason": string; };

export type TriageCase = { "projectId": string; "verificationMethod": "FIELD" | "DRONE" | "EXISTING_EVIDENCE"; "reason": string; };

/** Server kiểm bằng chứng; không suy no detections thành NO_DEFECT. */
export type CaseConclusion = { "conclusion": "DEFECT_FOUND" | "NO_DEFECT" | "DUPLICATE" | "OUT_OF_SCOPE"; "reason": string; "evidenceFileIds": Array<string>; "defectIds": Array<string>; };

export type Defect = { "id": string; "projectId": string; "typeCode": string; "severityCode": (string | null); "urgency": "NORMAL" | "SOON" | "EMERGENCY"; "pmFastTrackBlocked": boolean; "slabIds": Array<string>; "position": (Position | null); "status": string; "version": string; };

/** severityCode từ danh mục/enum hiện có; không tự đổi số enum DB. */
export type DefectAssessment = { "severityCode": string; "urgency": "NORMAL" | "SOON" | "EMERGENCY"; "pmFastTrackBlocked": boolean; "reason": string; "evidenceFileIds": Array<string>; };

export type VerifyDefect = { "decision": "VERIFIED" | "DISCARDED" | "NEEDS_MEASUREMENT"; "reason": string; "evidenceFileIds": Array<string>; "measurementIds": Array<string>; };

/** Chỉ ghi nhận đánh giá, không tự mở lại case đóng: Q07. */
export type RecurrenceAssessment = { "priorDefectId": string; "assessment": "PRIOR_REPAIR_UNACCEPTABLE" | "RECURRENCE" | "UNDETERMINED"; "reason": string; "evidenceFileIds": Array<string>; };

export type OrderRequest = { "defectIds": Array<string>; "reason": string; };

export type PolicyRule = { "defectTypeCode": string; "measurementType": string; "unit": string; "operator": "LT" | "LTE" | "GT" | "GTE" | "EQ"; "threshold": number; "repairMethodCode": string; "requiredEvidenceTypes": Array<"BEFORE" | "AFTER" | "MEASUREMENT">; "exclusions": Array<string>; };

/** Đề xuất cấu trúc rule v1; không tự điền threshold. Q02/Q03 chốt trước AVAILABLE. */
export type PolicyRequest = { "name": string; "rules": Array<PolicyRule>; "preparationList": Array<string>; };

export type PolicyVersion = { "id": string; "projectId": string; "name": string; "rules": Array<PolicyRule>; "preparationList": Array<string>; "status": "DRAFT" | "AVAILABLE" | "SUPERSEDED"; "version": string; };

/** INSPECT_AND_REPAIR phải có policyVersionId, một lỗi nhỏ được giao; server không suy từ số lỗi. Batch nhiều lỗi qua endpoint batch luôn MEASURE_ONLY. */
export type InspectionTaskCreate = { "defectIds": Array<string>; "mode": "INSPECT_ONLY" | "MEASURE_ONLY" | "INSPECT_AND_REPAIR"; "crewId": string; "policyVersionId"?: string; "dueAt"?: string; "destination"?: Position; };

export type InspectionBatchCreate = { "defectIds": Array<string>; "crewId": string; "plannedAt"?: string; };

export type InspectionTask = { "id": string; "projectId": string; "defectIds": Array<string>; "mode": "INSPECT_ONLY" | "MEASURE_ONLY" | "INSPECT_AND_REPAIR"; "crewId": string; "policyVersionId": (string | null); "status": string; "version": string; };

export type InspectionBatch = { "id": string; "taskIds": Array<string>; "mode": "MEASURE_ONLY"; "version": string; };

export type Measurement = { "defectId": string; "measurementType": string; "value": number; "unit": string; "instrument"?: string; "measuredAt": string; "position"?: Position; "evidenceFileIds": Array<string>; };

export type InspectionSubmit = { "taskVersion": string; "policyVersionId"?: string; "measurements": Array<Measurement>; "observedAt": string; };

export type InspectionSession = { "id": string; "taskId": string; "status": "SUBMITTED" | "NEEDS_REVIEW"; "measurementIds": Array<string>; "version": string; };

export type EvaluationRequest = { "sessionId": string; "policyVersionId": string; };

/** Eligibility khác authorization: task mode/PM block vẫn quyết định quyền sửa. */
export type Evaluation = { "id": string; "taskId": string; "policyVersionId": string; "result": "ELIGIBLE" | "NOT_ELIGIBLE" | "INSUFFICIENT_DATA"; "reasons": Array<string>; "version": string; };

export type RepairItemProposal = { "defectId": string; "methodDescription": string; "evidenceFileIds": Array<string>; "previousItemId"?: string; };

export type PackageCreate = { "items": Array<RepairItemProposal>; };

export type RepairItem = { "id": string; "defectId": string; "repairTrack": "FAST_TRACK" | "APPROVAL_TRACK" | "EMERGENCY"; "approvalStatus": string; "acceptanceStatus": string; "version": string; };

export type RepairPackage = { "id": string; "projectId": string; "items": Array<RepairItem>; "status": "DRAFT" | "SUBMITTED"; "version": string; };

/** reason bắt buộc khi decision != APPROVE; REJECT không đóng Defect. */
export type ItemDecision = { "decision": "APPROVE" | "REQUEST_EVIDENCE" | "REQUEST_RECONSIDER" | "REJECT"; "reason"?: string; };

export type RepairAssign = { "crewId": string; "reason": string; "dueAt"?: string; };

/** Q04: không coi offline đã nhận thu hồi; xung đột cần review, không last-write-wins. */
export type Reassignment = { "crewId": string; "reason": string; "handoverAcknowledgementId"?: string; };

/** APPROVAL_TRACK có repairItemId đã duyệt/giao; FAST_TRACK có originTaskId, evaluationId, capturedTaskVersion, policyVersionId. Không chờ PM duyệt số đo của task FT đủ điều kiện. */
export type StartAttempt = ({ "originTaskId"?: never; "repairItemId": string; "evaluationId"?: string; "beforeFileIds": Array<string>; "capturedTaskVersion"?: string; "policyVersionId"?: string; "startedAt": string; } | { "originTaskId": string; "repairItemId"?: never; "evaluationId": string; "beforeFileIds": Array<string>; "capturedTaskVersion": string; "policyVersionId": string; "startedAt": string; });

export type RepairAttempt = { "id": string; "repairItemId": string; "status": "IN_PROGRESS" | "SUBMITTED" | "NEEDS_EVIDENCE" | "REWORK_REQUIRED" | "PM_CHECKED" | "ACCEPTED"; "beforeFileIds": Array<string>; "afterFileIds": Array<string>; "version": string; };

export type SubmitAttempt = { "afterFileIds": Array<string>; "completedAt": string; "resultNotes": string; "measurementIds"?: Array<string>; };

/** ACCEPT bởi PM đóng FT + outbox Supervisor; APPROVAL_TRACK chỉ PM_checked, phải Supervisor xác nhận tiếp. reason bắt buộc nếu không ACCEPT. */
export type ReviewAttempt = { "decision": "ACCEPT" | "REQUEST_EVIDENCE" | "REWORK_REQUIRED"; "reason"?: string; };

/** D10 partial publication draft; requires Report-Defect mapping/public projection and remains PROPOSED_DELTA until implementation/tests. */
export type PublishCase = { "publicMessage": string; "afterFileIds": Array<string>; "defectIds": Array<string>; "reportIds"?: Array<string>; };

/** PM kích hoạt riêng; đóng nhiệm vụ tạm không resolve Defect; năng lực/giới hạn phải chốt. */
export type EmergencyCreate = { "defectIds": Array<string>; "crewId": string; "temporaryScope": string; "reason": string; };

/** Band labels là API đề xuất, map enum DD trước codegen. */
export type BandScope = { "routeVersionId": string; "segmentSetId": string; "segmentIds": Array<string>; "targetBand": "SURFACE" | "LEFT_EDGE" | "RIGHT_EDGE"; };

export type SurveyCreate = { "scope": Array<BandScope>; "surveyType": "BASELINE" | "PERIODIC" | "AD_HOC"; "operatorId": string; "dueAt"?: string; "accessPoint"?: Position; };

export type SurveyTask = { "id": string; "projectId": string; "scope": Array<BandScope>; "operatorId": string; "status": string; "version": string; };

export type SurveyReassign = { "operatorId": string; "reason": string; "dueAt"?: string; };

export type SupplementRequest = { "scope": Array<BandScope>; "reason": string; "operatorId": string; };

export type DatasetSubmit = { "videoFileIds": Array<string>; "telemetryFileIds": Array<string>; "recordedAt": string; "deviceId"?: string; "scope": Array<BandScope>; };

export type Dataset = { "id": string; "surveyTaskId": string; "dataVersionId": string; "integrityStatus": "VERIFIED" | "PENDING" | "INVALID"; "telemetryStatus": "PRESENT" | "MISSING" | "UNUSABLE"; "version": string; };

export type CoverageResult = { "scope": BandScope; "positionStatus": "PASS" | "FAIL" | "UNKNOWN"; "qualityStatus": "PASS" | "FAIL" | "UNKNOWN"; "coverageStatus": "SUFFICIENT" | "INSUFFICIENT" | "UNKNOWN"; "methodVersion": string; "reasons": Array<string>; };

export type BaselineConfirm = { "datasetId": string; "scope": Array<BandScope>; "reason": string; };

/** Export chỉ sau compatibility spike Q14; không gửi lệnh drone. */
export type MissionExport = { "scope": Array<BandScope>; "format": "KML" | "KMZ"; "accessPoint": Position; };

/** Reporter chỉ REPORT_PHOTO của mình, có thể chưa project. Các purpose nội bộ phải có projectId/targetId phù hợp. Mức byte/MIME theo config NFR. */
export type UploadCreate = { "purpose": "REPORT_PHOTO" | "BEFORE" | "AFTER" | "MEASUREMENT" | "SURVEY_VIDEO" | "TELEMETRY" | "ROUTE_SOURCE" | "DOCUMENT"; "projectId"?: string; "targetId"?: string; "fileName": string; "mediaType": string; "sizeBytes": number; "checksumSha256": string; };

export type UploadSession = { "id": string; "fileId": string; "status": "PENDING" | "UPLOADING" | "VERIFYING" | "VERIFIED" | "FAILED"; "partSizeBytes": number; "expiresAt": string; "version": string; };

export type UploadPartsRequest = { "partNumbers": Array<number>; };

export type UploadPartUrl = { "partNumber": number; "url": string; "expiresAt": string; };

/** Chỉ PUT scope đúng part, không cho đọc object; không log URL. */
export type UploadPartUrls = { "parts": Array<UploadPartUrl>; };

export type CompletedPart = { "partNumber": number; "etag": string; };

export type UploadComplete = { "parts": Array<CompletedPart>; "checksumSha256": string; };

export type FileMetadata = { "id": string; "status": "PENDING" | "VERIFIED" | "FAILED"; "checksumSha256": string; "mediaType": string; "sizeBytes": number; "version": string; };

/** Manifest persisted before 202; only server resolves file references/rights. */
export type ProcessingCreate = { "datasetId": string; "scope": BandScope; "modelVersionId": string; "preprocessingVersion": string; "configVersion": string; "mode": "MOCK" | "REAL"; };

export type Job = { "id": string; "status": "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "REQUIRES_REVIEW"; "resultId": (string | null); "attemptNumber": number; "version": string; "jobType": "AI_ANALYSIS" | "UPLOAD_VERIFY" | "EXPORT" | "MISSION_EXPORT" | "VALIDATION" | "TRAINING_EXPORT" | "RETENTION"; "error": (Error | null); "progressPercent"?: (number | null); };

export type Detection = { "detectionId": string; "frameFileId": string; "timestampMs": number; "typeCode": string; "confidence": number; "bbox": Array<number>; "estimatedPosition"?: Position; };

/** Service identity tied to job/attempt; immutable raw in storage verified. Late attempt may be archived without replacing current. */
export type AiResult = { "jobAttemptId": string; "manifestHash": string; "modelVersionId": string; "mode": "MOCK" | "REAL"; "rawResultFileId": string; "checksumSha256": string; "detections": Array<Detection>; };

/** 34A: PM duyệt/từ chối nhãn trong project; chỉ APPROVE mới được export training; AI không tự duyệt. Wire/runtime permission still requires verification. */
export type LabelReview = { "decision": "APPROVE" | "REJECT"; "reason": string; };

export type ValidationPair = { "groundTruthId": string; "derivedMeasurementId": string; };

export type ValidationRunCreate = { "pairs": Array<ValidationPair>; "modelVersionId": string; "datasetSplitId": string; "measurementType": string; "unit": string; };

export type ValidationResult = { "id": string; "usedCount": number; "excludedCount": number; "bias": (number | null); "mae": (number | null); "rmse": (number | null); "unit": string; "exclusionReasons": Array<string>; };

export type SyncMeasurement = { "operationId": string; "kind": "INSPECTION_SUBMIT"; "taskId": string; "expectedVersion": string; "capturedAt": string; "payload": InspectionSubmit; };

export type SyncStart = { "operationId": string; "kind": "REPAIR_START"; "taskId": string; "expectedVersion": string; "capturedAt": string; "payload": StartAttempt; };

export type SyncAttemptSubmit = { "operationId": string; "kind": "REPAIR_SUBMIT"; "attemptId": string; "expectedVersion": string; "capturedAt": string; "payload": SubmitAttempt; };

/** D02/D07 offline evaluation after measurement. This is a proposed contract extension; server replay must recheck task/policy snapshot and current authority before APPLIED. */
export type SyncFastTrackEvaluate = { "operationId": string; "kind": "FAST_TRACK_EVALUATE"; "taskId": string; "expectedVersion": string; "capturedAt": string; "measurementSessionId": string; "localEvaluationId": string; "payload": EvaluationRequest; };

export type SyncOperation = (SyncMeasurement | SyncStart | SyncAttemptSubmit | SyncFastTrackEvaluate);

/** Proposed contract extension for D02/D07. Process in dependency order with per-operation receipts; ACK only after durability. Legacy clients with three kinds remain compatible until schema/runtime rollout is approved. trước. Thực hiện phase submit sau khi đã map local→server ID từ start response. */
export type SyncBatch = { "deviceId": string; "operations": Array<SyncOperation>; };

export type SyncOutcome = { "operationId": string; "status": "APPLIED" | "DUPLICATE" | "CONFLICT" | "REJECTED"; "resourceId": (string | null); "version": (string | null); "error": (Error | null); };

export type SyncResult = { "results": Array<SyncOutcome>; };

export type DashboardMetric = { "code": string; "value": (number | null); "unit": string; "numerator"?: (number | null); "denominator"?: (number | null); "sourceIds"?: Array<string>; "missingReason": (string | null); };

export type Dashboard = { "asOf": string; "metricDefinitionVersion": string; "metrics": Array<DashboardMetric>; "isPartial": boolean; };

export type ExportRequest = { "projectId": string; "segmentIds"?: Array<string>; "defectIds"?: Array<string>; "periodFrom"?: string; "periodTo"?: string; "format": "PDF" | "ZIP"; "includeOriginalFiles": boolean; };

export type Event = { "id": string; "occurredAt": string; "actorId": (string | null); "action": string; "resourceType": string; "resourceId": string; "message": string; };

export type Notification = { "id": string; "message": string; "resourceId": (string | null); "read": boolean; "occurredAt": string; "version": string; };

export type ModelCreate = { "name": string; "artifactFileId": string; "artifactSha256": string; "datasetSplitId": string; "licenseReference": string; };

export type ModelVersion = { "id": string; "name": string; "artifactSha256": string; "status": "DRAFT" | "ACTIVE" | "RETIRED"; "version": string; };

export type DeletionRequest = { "projectId": string; "fileIds"?: Array<string>; "reason": string; };

export type RetentionDecision = { "decision": "APPROVE" | "REJECT"; "reason": string; };

export type RetentionRequest = { "id": string; "projectId": string; "status": "PENDING" | "APPROVED" | "REJECTED" | "EXECUTED" | "BLOCKED"; "version": string; };

export type LegalHoldRequest = { "enabled": boolean; "reason": string; };

/** Q12 PM xác nhận là đề xuất, không tự ban hành quyền trước quyết định. */
export type AccessPointUpdate = { "position": Position; "reason": string; };

/** Thành viên không bắt buộc có account; lead phải có quyền. */
export type CrewCreate = { "name": string; "leadUserId": string; "memberNames": Array<string>; };

export type Crew = { "id": string; "projectId": string; "name": string; "leadUserId": string; "memberNames": Array<string>; "version": string; };

export type DeviceCreate = { "name": string; "model": string; "firmware": string; "parserVersion": string; };

export type Device = { "id": string; "name": string; "model": string; "firmware": string; "parserVersion": string; "version": string; };

export type CatalogEntry = { "code": string; "label": string; "active": boolean; "version": string; };

export type CatalogEntryUpdate = { "label": string; "active": boolean; "reason": string; };

export type ReminderConfig = { "surveyLeadDays": number; "warrantyLeadDays": number; "version": string; };

export type ReminderConfigUpdate = { "surveyLeadDays": number; "warrantyLeadDays": number; "reason": string; };

export type NotificationPage = { "items": Array<Notification>; "nextCursor": (string | null); "asOf": string; };

export type ProjectPage = { "items": Array<Project>; "nextCursor": (string | null); "asOf": string; };

export type CrewPage = { "items": Array<Crew>; "nextCursor": (string | null); "asOf": string; };

export type PublicReportPage = { "items": Array<PublicReport>; "nextCursor": (string | null); "asOf": string; };

export type CasePage = { "items": Array<Case>; "nextCursor": (string | null); "asOf": string; };

export type DefectPage = { "items": Array<Defect>; "nextCursor": (string | null); "asOf": string; };

export type CoverageResultPage = { "items": Array<CoverageResult>; "nextCursor": (string | null); "asOf": string; };

export type EventPage = { "items": Array<Event>; "nextCursor": (string | null); "asOf": string; };

export type CatalogEntryPage = { "items": Array<CatalogEntry>; "nextCursor": (string | null); "asOf": string; };

export type InspectionTaskPage = { "items": Array<InspectionTask>; "nextCursor": (string | null); "asOf": string; };

export type RepairItemPage = { "items": Array<RepairItem>; "nextCursor": (string | null); "asOf": string; };

export type SurveyTaskPage = { "items": Array<SurveyTask>; "nextCursor": (string | null); "asOf": string; };

export type EvidenceReference = { "fileId": string; "purpose": string; "source": string; "capturedAt": (string | null); "checksumSha256": string; };

/** Không có offline_expires_at; auth token expiry là riêng. Snapshot metadata không chứng minh file bytes đã tải bền vững. Kiểm download/checksum local trước ready. */
export type TaskSnapshot = { "snapshotId": string; "capturedAt": string; "task": InspectionTask; "policy": (PolicyVersion | null); "assignmentVersion": string; "pmFastTrackBlocked": boolean; "evidence": Array<EvidenceReference>; "destination": (Position | null); };

/** Ít nhất nguồn report hoặc cặp job/detection; PM giữ phát hiện sơ bộ, chưa tự VERIFIED. */
export type DefectCreate = { "typeCode": string; "sourceReportId"?: string; "sourceDetectionId"?: string; "sourceJobId"?: string; "position"?: Position; "evidenceFileIds": Array<string>; };

export type SlabLinks = { "slabIds": Array<string>; "reason": string; };

export type PlanCreate = { "scope": Array<BandScope>; "plannedAt": string; "surveyType": "BASELINE" | "PERIODIC" | "AD_HOC"; };

export type SurveyPlan = { "id": string; "projectId": string; "scope": Array<BandScope>; "plannedAt": string; "status": "PLANNED" | "POSTPONED" | "TASK_CREATED"; "version": string; };

/** Chỉ nhãn đã được PM duyệt, có quyền sử dụng. */
export type TrainingExportRequest = { "projectId": string; "labelIds": Array<string>; "datasetSplitId": string; };

export type JobPage = { "items": Array<Job>; "nextCursor": (string | null); "asOf": string; };

export type WorkOrder = { "id": string; "projectId": string; "defectIds": Array<string>; "version": string; };

export type ProposalRevision = { "methodDescription": string; "evidenceFileIds": Array<string>; "reason": string; };

export type ReworkCreate = { "beforeFileIds": Array<string>; "startedAt": string; "reason": string; };
